# -*- coding: utf-8 -*-
"""API_Request

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jI-a0S13D3AXPRrQRK6kEiIMYaBBAYWa
"""

# Define your API address
url = "Enter your API address"
keep_id = []

# Example of observation parameters
script = dict([("ObjectName", "M32"),
                ("StationName", "SRO"),
                ("RA", ra.replace("h", ":").replace("m", ":").replace("s", "")),
                ("DEC", dec.replace("d", ":").replace("m", ":").replace("s", "")),
                ("BinningXY", "1,1"),
                ("CadenceInterval", "00:00:00"),
                ("MaxAirmass", "3"),
                ("PA", "0"),
                ("Dither", "0"),
                ("ExpiryDate", "{}".format(exp_obs.iso)),
                ("StartDate", "{}".format(sunset_tonight.iso)),
                ("EndDate", "{}".format(end_obs.iso)),
                ("ExposuresMode", "1"),
                ("M3Port", "1"),
                ("Filter", ["B", "V", "R", "I"]),
                ("Suffix", ["{}_B".format(GW_event),"{}_V".format(GW_event),"{}_R".format(GW_event), "{}_I".format(GW_event)]),
                ("Exposure", ["120","120","120", "120"]),
                ("Repeat", ["5","5","5", "5"])
              ])

# Sending the API request
payload = json.dumps({"script": [ script] })
print(payload, "\n")

headers = {
            'Content-Type': 'application/json',
            'TRT': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZDk0MTdhNzQzNzUxYzBmNmNiZGRjMjAiLCJuYW1lIjoiS2FudGhhbmFrb3JuIE5veXNlbmEiLCJncm91cElkIjoxLCJncm91cE5hbWUiOiJyZXNlYXJjaGVyIiwicHJpb3JpdHlJZCI6IjY1OGFjYmJlMDhhYmY2MDI3ODNhMGFjOCIsInByaW9yaXR5Ijo5NSwic3RhcnREYXRlIjoiMjAyNC0wMS0wMVQwMDowMTowMC4wMDBaIiwiZXhwaXJlRGF0ZSI6IjIwMjQtMDQtMzBUMjM6NTk6MDAuMDAwWiIsImlhdCI6MTcwNDk1ODkwMiwiZXhwIjoxNzE0NDYyOTAyfQ.v9bQFhmrThw5sCpD1OAlpHWQa3v_v10EgeIuTxge2yE'
        }
        if True:
            response = requests.request("POST", url, headers=headers, data=payload)
            keep_id.append(response.text)
            print(response.text)

    else:
        pass